# https://taskfile.dev

version: '3'
silent: true

tasks:
  default:
    cmds:
      - DEBUG=true go run . {{.CLI_ARGS}}
    interactive: true
    desc: Run

  debug:
    cmds:
      - printf "~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n―――――――――――――――――――――――――――――――――――――――――――――――\n" > ./debug.log
      - DEBUG=true LOG_LEVEL={{.LOG_LEVEL}} go run . {{.CLI_ARGS}}
    interactive: true
    desc: Run in debug mode. Run `task logs` to watch the logs.

  install:
    desc: Install the application
    vars:
      LDFLAGS: '{{if .VERSION}}-ldflags="-X github.com/hagelstam/ouractl/internal/version.Version={{.VERSION}}"{{end}}'
    cmds:
      - go install {{.LDFLAGS}} -v .
    sources:
      - ./**/*.go
      - go.mod

  logs:
    cmds:
      - rm -f ./debug.log
      - touch ./debug.log
      - tail -f ./debug.log
    interactive: true
    desc: Tail the debug logs

  lint:
    desc: Run base linters
    cmds:
      - golangci-lint run --path-mode=abs --config=".golangci.yml" --timeout=5m
    env:
      GOEXPERIMENT: null

  lint-fix:
    desc: Run base linters and fix issues
    cmds:
      - golangci-lint run --path-mode=abs --config=".golangci.yml" --timeout=5m --fix
    env:
      GOEXPERIMENT: null

  test:
    cmds:
      - go test -v ./...
    desc: Run tests

  fmt:
    desc: Run golangci-lint fmt
    cmds:
      - golangci-lint fmt

  release:
    cmds:
      - git checkout main
      - git tag $(svu next)
      - git push --tags
